### ISSUE TITLE
How to open 'FloatingActionMenu' when start activity

### ISSUE THREAD

**Issue by echoaiya** [oguzbilgener/CircularFloatingActionMenu#50]
protected void onResume() {
		// TODO Auto-generated method stub
		super.onResume();
		
		if(mActionMenu != null && !mActionMenu.isOpen()) {
			mActionMenu.open(true);
		}
	}

I did this to open 'FloatingActionMenu' in 'MenuWithFABActivity', but it didn't work!
Please help!

**Comment by SanjaySolanki001** [comment]
Did you got the solution @echoaiya
